# Google's AI API library.
import google.generativeai as genai

# This is where your google API key is inputed, this key should be kept private and for larger projects, a seperate database might be accessed to get the key.
GOOGLE_API_KEY="YOUR_API_KEY_HERE"
genai.configure(api_key=GOOGLE_API_KEY)

# This class interacts with the gemini API to ask the following question: 
# "Please take the following article and summarize it in 50 words or less, here is the article: (article content here)"
# It uses the gemini-pro model as this model works best for text.
class geminiAPI():
    def __init__(self):
        # Initializes the model to gemini-pro
        self.model = genai.GenerativeModel('gemini-pro')

    # Returns the summary of the article generated by gemini.
    # Note: The prompt asks for 50 words or less, however sometimes it has returned 63 words on some of my tests, so it trys to keep it around 50 words +-15.
    def geminiSummary(self,data):
        message = str("Please take the following article and summarize it in 50 words or less, here is the article: "+data)
        summary = self.model.generate_content(message)
        return str(summary.text)

